m2miage_greenergy_project_api:
    pattern:  /{version}/{year}/{threshold}/{household}.{_format}
    defaults:
            _controller: m2miagegre.api.controller:apiAction
            _format: json
    requirements:
           _method: GET
