m2miage_greenergy_project_api:
    pattern:  /{version}/{year}/{threshold}/{household}.{_format}
    defaults:
            _controller: m2miagegre.api.controller:apiAction
            _format: json
    requirements:
           _method: GET

m2miage_greenergy_project_api_v2:
    pattern: /{version}/{household}/{year}_{month}_{day}.json
    defaults:
            _controller: m2miagegre.api.controller:apiActionV2
            _format: json
    requirements:
           _method: GET
