parameters:
#    m2miage_greenergy_project.example.class: m2miageGre\energyProjectBundle\Example

services:
#    m2miage_greenergy_project.example:
#        class: %m2miage_greenergy_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
